bowlpicks/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.detail import DetailView
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

from django.contrib import admin
admin.autodiscover()

from bowlpicks.core.views import HomePage
from bowlpicks.profiles.models import Profile
from bowlpicks.profiles.views import profile_detail, delete_player, make_player_current


urlpatterns = patterns('',
    url(r'^$', HomePage.as_view(), {}, 'homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/password/reset/$',
        password_reset,
        {'template_name': 'registration/forgot_password.html'},
        name='password_reset'),
    url(r'^accounts/password/reset/done/$',
        password_reset_done,
        {'template_name': 'registration/password_reset_done.html'}),
    url(r'^accounts/password/reset/done/$',
        password_reset_done,
        {'template_name': 'registration/password_reset_done.html'}),
    url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        {'template_name': 'registration/password_reset_confirm.html'}),
    url(r'^reset/done/$',
        password_reset_complete,
        {'template_name': 'registration/password_reset_complete.html'}),
    url(r'^accounts/', include('registration.backends.default.urls')),
    (r'^contact/thankyou/$', 'bowlpicks.contact.views.thankyou'),
    (r'^contact/$', 'bowlpicks.contact.views.contactview', {}, 'contact'),
    (r'^contact/email_everyone/', 'bowlpicks.contact.views.email_everyone', {}, 'email_everyone'),
    url(r'^picks/', include('bowlpicks.core.urls.picks')),
    url(r'^profiles/(?P<pk>\d+)/$', profile_detail, {}, 'bowlpicks_profile_detail'),
    url(r'^profiles/(?P<pk>\d+)/picks$', DetailView.as_view(
                template_name="profiles/profile_picks.html",
                model=Profile), {}, 'profile_picks'),
    url(r'profiles/delete_player/(?P<player_id>\d+)/$', delete_player, {}, 'bowlpicks_delete_player'),
    url(r'profiles/make_player_current/(?P<player_id>\d+)/$', make_player_current, {}, 'bowlpicks_make_player_current'),
    url(r"^profiles/", include("idios.urls")),
)

bowlpicks/core/models.py
from django.db import models
import datetime
from django.http import HttpRequest
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
import urllib2

from bowlpicks.profiles.models import Player, PlayerRanking

def get_current_season():
    return Season.objects.current()

class SeasonManager(models.Manager):
    def current(self):
        return self.filter(current=True)[0]


class Season(models.Model):
    year_start = models.CharField(max_length=10)
    year_end = models.CharField(max_length=10)
    current = models.BooleanField(default=False)
    freeze_date = models.DateField(blank=True, null=True)

    objects = SeasonManager()

    def __unicode__(self):
        return u"%s-%s" % (self.year_start, self.year_end)

    def leaders(self):
        return PlayerRanking.objects.filter(season=self)[:10]


    def get_picks(self):
        return Pick.objects.filter(game__season=self)

    @property
    def is_froze(self):
        return datetime.date.today() >= self.freeze_date


class Conference(models.Model):

    name = models.CharField(max_length=50)
    abbr = models.CharField(max_length=10)

    def __unicode__(self):
        return u"%s" % self.abbr


class School(models.Model):

    name = models.CharField(max_length=100)
    abbr = models.CharField(max_length=100)
    mascot = models.CharField(max_length=100)
    conference = models.ForeignKey(Conference)
    color = models.CharField(max_length=15, blank=True, null=True)

    class Meta:
        ordering = ['name', ]

    def __unicode__(self):
        return u"%s %s" % (self.name, self.mascot)


class Team(models.Model):

    school = models.ForeignKey(School)
    season = models.ForeignKey(Season, default=get_current_season(), blank=True, null=True)
    record = models.CharField(max_length=20, blank=True, null=True)
    rank = models.IntegerField(blank=True, null=True)

    def __unicode__(self):
        """
        2011-2012 - Colorado State Rams (13-2-1)
        """
        return "%s - %s (%s)" % (self.season, self.school, self.record)

EST = 1
CST = 2
MST = 3
PST = 4
TIMEZONES = (
    (EST, "EST"),
    (CST, "CST"),
    (MST, "MST"),
    (PST, "PST"),
)


class GameManger(models.Manager):
    def today(self, *args, **kwargs):
        return self.filter(
            date__lt=datetime.datetime.today() + datetime.timedelta(days=1),
            date__gte=datetime.datetime.today()).order_by('date')

    def tomorrow(self, *args, **kwargs):
        tomorrow = datetime.datetime.today() + datetime.timedelta(days=1)
        return self.filter(
            date__lt=tomorrow + datetime.timedelta(days=1),
            date__gte=tomorrow).order_by('date')



class Game(models.Model):
    date = models.DateTimeField()
    timezome = models.IntegerField(choices=TIMEZONES, default=EST)
    season = models.ForeignKey(Season, default=get_current_season())
    name = models.CharField(max_length=100)
    channel = models.CharField(max_length=100, default="Change Me")
    away_team = models.ForeignKey(Team, related_name="away_team", blank=True, null=True)
    away_score = models.IntegerField(blank=True, null=True)
    home_team = models.ForeignKey(Team, related_name="home_team", blank=True, null=True)
    home_score = models.IntegerField(blank=True, null=True)

    require_tie_breaker = models.BooleanField(default=False)

    objects = GameManger()

    class Meta:
        ordering = ['date', ]

    def __unicode__(self):
        return u"(%s) %s" % (self.season, self.name)

    @property
    def short_name(self):
        return u"%s vs %s" % (self.home_team.school.abbr, self.away_team.school.abbr)

    def home_picks(self):
        return self.pick_set.filter(
            winner=self.home_team,
            player__active=True)

    def away_picks(self):
        return self.pick_set.filter(
            winner=self.away_team,
            player__active=True)

    def away_percent(self):
        try:
            value = (float(self.away_picks().count()) / float(self.pick_set.filter(player__active=True).count())) * 100
        except ZeroDivisionError:
            value = 0
        return round(value)

    def home_percent(self):
        try:
            value = (float(self.home_picks().count()) / float(self.pick_set.filter(player__active=True).count())) * 100
        except ZeroDivisionError:
            value = 0
        return round(value)

    @property
    def winner_home(self):
        return self.home_picks().count() > self.away_picks().count()

    @property
    def winner_away(self):
        return self.away_picks().count() > self.home_picks().count()

    @property
    def winner(self):
        if self.home_score > self.away_score:
            return self.home_team
        elif self.away_score > self.home_score:
            return self.away_team
        else:
            return None


class PickManager(models.Manager):
    def curent_season(self):
        season = Season.objects.filter(current=True)[0]
        return self.filter(game__season=season).order_by('game__date')


class Pick(models.Model):

    player = models.ForeignKey("profiles.Player")
    game = models.ForeignKey(Game)
    winner = models.ForeignKey(Team, blank=True, null=True)
    home_score = models.IntegerField(blank=True, null=True)
    away_score = models.IntegerField(blank=True, null=True)

    objects = PickManager()

    def __unicode__(self):
        return u"%s - %s" % (self.player, self.winner)

    @property
    def correct(self):
        if self.winner:
            return self.winner == self.game.winner
        else:
            return None


def pick_post_save(sender, instance, signal, *args, **kwargs):
    pick = instance
    player = pick.player



def game_post_save(sender, instance, signal, *args, **kwargs):
    season = Season.objects.current()
    for player in Player.objects.all():
        rank, created = PlayerRanking.objects.get_or_create(
            season=season,
            player=player)

        rank.correct = player.points
        rank.wrong = player.wrong
        rank.save()


post_save.connect(pick_post_save, sender=Pick)
post_save.connect(game_post_save, sender=Game)

templates/base.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <!-- Use the .htaccess and remove these lines to avoid edge case issues.
       More info: h5bp.com/b/378 -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block title %}BowlPicks - {% block subtitle %}{% endblock subtitle %}{% endblock title %}</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  {% block css %}
  <!-- CSS: implied media=all -->
  <!-- CSS concatenated and minified via ant build script-->
  <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
  {% block extended_css %}{% endblock extended_css %}
  <!-- end CSS-->
  {% endblock css %}


  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except for Modernizr / Respond.
       Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
       For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
  <script src="{{STATIC_URL }}js/libs/modernizr-2.0.6.min.js"></script>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url homepage %}">BowlPicker</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              {% block nav %}
                <li class="active"><a href="{% url homepage %}">Home</a></li>
                <li><a href="{% url pick_list %}">Pick List</a></li>
                <li><a href="/help/">Help</a></li>
              {% endblock nav %}
            </ul>
            <ul class="nav pull-right">
                {% if user.is_anonymous %}
                  <li class="divider-vertical"></li>
                  <li><a href="{% url auth_login %}">Log in</a></li>
                  <li class="divider-vertical"></li>
                  <li><a href="{% url registration_register %}">Register</a></li>
                {% else %}
                  <li class="menu">
                  <li class="divider-vertical"></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.get_profile }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="{% url bowlpicks_profile_detail user.get_profile.pk %}"><i class="icon-user"></i> Profile</a></li>
                      <li><a href="{% url profile_picks user.get_profile.pk %}"><i class="icon-pencil"></i> My Picks</a></li>
                      <li class="divider"></li>
                      {% if user.is_staff %}
                        <li><a href="{% url email_everyone %}">Email Everyone</a></li>
                        <li class="divider"></li>
                      {% endif %}
                      <li><a href="{% url auth_logout %}"><i class="icon-off"></i> Log out</a></li>
                    </ul>
                  </li>
                {% endif %}
                <li class="divider-vertical" style="padding:-5px;margin-right:0px;"></li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container bowlpick-container">

      <div class="content">
      {% block header %}
        <div class="page-header">
          <h1>{{ season }} Bowl Picks</h1>
        </div>
      {% endblock header %}
      {% block content %}
        <div class="row">
          <div class="span10">
            <h2>Main content</h2>
          </div>
          <div class="span4">
            <h3>Secondary content</h3>
          </div>
        </div>
      </div>
      {% endblock content %}

      {% block footer %}
        <footer>
          <p>&copy; <a href="http://www.nicklang.com">Nick Lang</a> 2011</p>
        </footer>
      {% endblock footer %}

    </div> <!-- /container -->
  {% block js %}
  <!-- JavaScript at the bottom for fast page loading -->

  <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
  <script src="{{ STATIC_URL}}js/jquery.js"></script>


  <!-- scripts concatenated and minified via ant build script-->
  <script defer src="{{ STATIC_URL }}js/bootstrap.js"></script>
  <script defer src="{{ STATIC_URL }}js/prettify.js"></script>
  <script defer src="{{ STATIC_URL }}js/plugins.js"></script>
  <script defer src="{{ STATIC_URL }}js/script.js"></script>
  <script defer src="{{ STATIC_URL }}js/jquery.ba-dotimeout.min.js"></script>
  <script defer src="{{ STATIC_URL }}js/bootstrap-twipsy.js"></script>
  <script defer src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>
  <script defer src="{{ STATIC_URL }}js/bootstrap-alerts.js"></script>
  <!-- end scripts-->


  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
  {% block extended_js %}{% endblock extended_js %}
  {% endblock js %}


</body>
</html>

templates/footer.html
<p>&copy; Nick Lang {% now "Y" %}<p>

templates/homepage.html
{% extends "new_base.html" %}

{% block subtitle %}
    Bowlpicks
{% endblock subtitle %}

{% block extended_css %}
{% endblock extended_css %}


{% block container %}
    <div class="container-fluid">
      <div class="row-fluid">
        {% block leaderboard %}
          <div class="span3">
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header"><i class="icon-signal"></i> Leaderboard</li>
                <ol>
                  {% for player in season.leaders %}
                    <li>{{ player.player }} <strong>({{ player.correct }})</strong></li>
                  {% endfor %}
                </ol>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        {% endblock leaderboard %}


        <div class="span9">
          <div class="hero-unit">
            {% if todays_games %}
              {% for game in todays_games %}
                <div class="row-fluid">
            <div class="page-header">
              <h2>{{ game.name }} <small>{{ game.date|date:"g:i a" }} {{ game.get_timezome_display }} on {{ game.channel }}</small></h2>
            </div>

            <div class="span2">
              <div style="font-size: 100px;">
                <span class="chartwell pies">
                  <span style="color: {{ game.home_team.school.color }}">{{ game.home_percent }}</span>
                  <span style="color: {{ game.away_team.school.color }}">{{ game.away_percent }}</span>
                  <span style="color: #fff">A</span> <!-- medium sized white centre piece -->
                </span>
              </div>
            </div>

            <div class="span3">
              <p>{% if game.home_score %}<span class="badge  {% if game.winner == game.home_team %}badge-success{% endif %}">{{ game.home_score }}</span>{% endif %}
                <small>
                {% if game.home_team.rank %}
                  ({{ game.home_team.rank }})
                {% endif %}
                </small>
                <strong style="color: {{ game.home_team.school.color }}">{{ game.home_team.school.abbr }} {% if game.winner_home %}<i class="icon-star"></i>{% endif %} </strong>
                ({{ game.home_team.record }})</br>
                <small>{{ game.home_team.school.conference }}</small>
              </p>
            </div>



            <div class="span1">
              <h3>VS</h3>
            </div>

            <div class="span3">
              <p>{% if game.away_score %}<span class="badge {% if game.winner == game.away_team %}badge-success{% endif %}">{{ game.away_score }}</span>{% endif %}
                <small>
                {% if game.away_team.rank %}
                  ({{ game.away_team.rank }})
                {% endif %}
                </small>
                <strong style="color: {{ game.away_team.school.color }}">{{ game.away_team.school.abbr }} {% if game.winner_away %}<i class="icon-star"></i>{% endif %} </strong>
                ({{ game.away_team.record }})</br>
                <small>{{ game.away_team.school.conference }}</small>
              </p>
            </div>


          </div>
              {% endfor %}
            {% else %}
              <h2>No games today! :(</h2>
            {% endif %}
          </div>

          {% for game in games %}
          <div class="row-fluid">
            <div class="page-header">
              <h2>{{ game.name }} <small>{{ game.date|date:"g:i a" }} {{ game.get_timezome_display }} on {{ game.channel }}</small></h2>
            </div>

            <div class="span2">
              <div style="font-size: 100px;">
                <span class="chartwell pies">
                  <span style="color: {{ game.home_team.school.color }}">{{ game.home_percent }}</span>
                  <span style="color: {{ game.away_team.school.color }}">{{ game.away_percent }}</span>
                  <span style="color: #fff">A</span> <!-- medium sized white centre piece -->
                </span>
              </div>
            </div>

            <div class="span3">
              <p>{% if game.home_score %}<span class="badge  {% if game.winner == game.home_team %}badge-success{% endif %}">{{ game.home_score }}</span>{% endif %}
                <small>
                {% if game.home_team.rank %}
                  ({{ game.home_team.rank }})
                {% endif %}
                </small>
                <strong style="color: {{ game.home_team.school.color }}">{{ game.home_team.school.abbr }} {% if game.winner_home %}<i class="icon-star"></i>{% endif %} </strong>
                ({{ game.home_team.record }})</br>
                <small>{{ game.home_team.school.conference }}</small>
              </p>
            </div>



            <div class="span1">
              <h3>VS</h3>
            </div>

            <div class="span3">
              <p>{% if game.away_score %}<span class="badge {% if game.winner == game.away_team %}badge-success{% endif %}">{{ game.away_score }}</span>{% endif %}
                <small>
                {% if game.away_team.rank %}
                  ({{ game.away_team.rank }})
                {% endif %}
                </small>
                <strong style="color: {{ game.away_team.school.color }}">{{ game.away_team.school.abbr }} {% if game.winner_away %}<i class="icon-star"></i>{% endif %} </strong>
                ({{ game.away_team.record }})</br>
                <small>{{ game.away_team.school.conference }}</small>
              </p>
            </div>


          </div>
          {% endfor %}

        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        {% include "footer.html" %}
      </footer>

    </div><!--/.fluid-container-->
  {% endblock container %}

templates/new_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bowlpicker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Le styles -->
    {% block css %}
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/css/bootstrap-combined.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
      <script src="excanvas.min.js"></script>
    <![endif]-->
    {% block extened_css %}{% endblock extened_css %}
    {% endblock css %}

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{% url homepage %}">Bowlpicks</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="{% url homepage %}">Home</a></li>
              <li><a href="{% url pick_list %}">Pick List</a></li>
              <li><a href="/help/">Help</a></li>
            </ul>
            <ul class="nav pull-right">
              {% if user.is_anonymous %}
                <li><a href="{% url auth_login %}">Log in</a></li>
                <li class="divider-vertical"></li>
                <li><a href="{% url registration_register %}">Register</a></li>
              {% else %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.get_profile }} <b class="caret"></b></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url bowlpicks_profile_detail user.get_profile.pk %}"><i class="icon-user"></i> Profile</a></li>
                    <li><a href="{% url profile_picks user.get_profile.pk %}"><i class="icon-check"></i> My Picks</a></li>
                    <li class="divider"></li>
                    {% if user.is_staff %}
                      <li><a href="{% url email_everyone %}">Email Everyone</a></li>
                      <li class="divider"></li>
                    {% endif %}
                    <li><a href="{% url auth_logout %}"><i class="icon-off"></i> Log out</a></li>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

  {% block container %}
  {% endblock container %}

  {% block js %}
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_URL }}js/jquery.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.1/js/bootstrap.min.js"></script>

    <script src="{{ STATIC_URL }}js/chartwell.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_bars.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_barsvertical.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_lines.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_pies.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_radar.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_rings.min.js"></script>
    <script src="{{ STATIC_URL }}js/chartwell_rose.min.js"></script>
    <script>
      $(document).ready(function(){
        FFChartwell()
      })
    </script>
    {% block extended_js %}{% endblock extended_js %}
  {% endblock js %}

  </body>
</html>